name: madminer
channels:
- pytorch
- anaconda
- defaults
dependencies:
- python=3.7.*
- h5py
- matplotlib>=2.0.0
- numpy>=1.20.0
- scipy>=1.0.0
- sympy>=0.7.4
- pytorch>=1.0.0
- pytest
- pip
- pip:
  - particle>=0.16.0
  - uproot3>=3.14.1
  - vector>=0.8.4
