ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=3)

      DOUBLE PRECISION MDL_MP,MDL_MT,MDL_MW,MDL_MZ,MDL_MTA,MDL_MC
     $ ,MDL_MB,MDL_MH,MDL_MM

      COMMON/MASSES/ MDL_MP,MDL_MT,MDL_MW,MDL_MZ,MDL_MTA,MDL_MC,MDL_MB
     $ ,MDL_MH,MDL_MM


      DOUBLE PRECISION MDL_WH1,MDL_WTAU,MDL_WW,MDL_WT,MDL_WZ,MDL_WH

      COMMON/WIDTHS/ MDL_WH1,MDL_WTAU,MDL_WW,MDL_WT,MDL_WZ,MDL_WH


      DOUBLE COMPLEX GC_1, GC_62, GC_91, GC_92, GC_93, GC_94, GC_117,
     $  GC_145

      COMMON/COUPLINGS/ GC_1, GC_62, GC_91, GC_92, GC_93, GC_94,
     $  GC_117, GC_145

