ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of EWdim6-full'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_62 = ', GC_62
      WRITE(*,2) 'GC_91 = ', GC_91
      WRITE(*,2) 'GC_92 = ', GC_92
      WRITE(*,2) 'GC_93 = ', GC_93
      WRITE(*,2) 'GC_94 = ', GC_94
      WRITE(*,2) 'GC_117 = ', GC_117
      WRITE(*,2) 'GC_145 = ', GC_145
