ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of EWdim6-full'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_11 = ', GC_11
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_4 = ', GC_4
      WRITE(*,2) 'GC_6 = ', GC_6
      WRITE(*,2) 'GC_8 = ', GC_8
      WRITE(*,2) 'GC_62 = ', GC_62
      WRITE(*,2) 'GC_71 = ', GC_71
      WRITE(*,2) 'GC_72 = ', GC_72
      WRITE(*,2) 'GC_79 = ', GC_79
      WRITE(*,2) 'GC_145 = ', GC_145
