ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_CWWWL2 = ', MDL_CWWWL2
      WRITE(*,*) 'mdl_CWL2 = ', MDL_CWL2
      WRITE(*,*) 'mdl_CBL2 = ', MDL_CBL2
      WRITE(*,*) 'mdl_CPWWWL2 = ', MDL_CPWWWL2
      WRITE(*,*) 'mdl_CPWL2 = ', MDL_CPWL2
      WRITE(*,*) 'mdl_CphidL2 = ', MDL_CPHIDL2
      WRITE(*,*) 'mdl_CphiWL2 = ', MDL_CPHIWL2
      WRITE(*,*) 'mdl_CphiBL2 = ', MDL_CPHIBL2
      WRITE(*,*) 'aEWM1 = ', AEWM1
      WRITE(*,*) 'mdl_Gf = ', MDL_GF
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'mdl_lamWS = ', MDL_LAMWS
      WRITE(*,*) 'mdl_AWS = ', MDL_AWS
      WRITE(*,*) 'mdl_rhoWS = ', MDL_RHOWS
      WRITE(*,*) 'mdl_etaWS = ', MDL_ETAWS
      WRITE(*,*) 'mdl_ymc = ', MDL_YMC
      WRITE(*,*) 'mdl_ymb = ', MDL_YMB
      WRITE(*,*) 'mdl_ymt = ', MDL_YMT
      WRITE(*,*) 'mdl_ymm = ', MDL_YMM
      WRITE(*,*) 'mdl_ymtau = ', MDL_YMTAU
      WRITE(*,*) 'mdl_MZ = ', MDL_MZ
      WRITE(*,*) 'mdl_MC = ', MDL_MC
      WRITE(*,*) 'mdl_MT = ', MDL_MT
      WRITE(*,*) 'mdl_MB = ', MDL_MB
      WRITE(*,*) 'mdl_MH = ', MDL_MH
      WRITE(*,*) 'mdl_MM = ', MDL_MM
      WRITE(*,*) 'mdl_MTA = ', MDL_MTA
      WRITE(*,*) 'mdl_MP = ', MDL_MP
      WRITE(*,*) 'mdl_WZ = ', MDL_WZ
      WRITE(*,*) 'mdl_WW = ', MDL_WW
      WRITE(*,*) 'mdl_WT = ', MDL_WT
      WRITE(*,*) 'mdl_WH = ', MDL_WH
      WRITE(*,*) 'mdl_WTau = ', MDL_WTAU
      WRITE(*,*) 'mdl_WH1 = ', MDL_WH1
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_lamWS__exp__2 = ', MDL_LAMWS__EXP__2
      WRITE(*,*) 'mdl_CKM1x1 = ', MDL_CKM1X1
      WRITE(*,*) 'mdl_CKM1x2 = ', MDL_CKM1X2
      WRITE(*,*) 'mdl_complexi = ', MDL_COMPLEXI
      WRITE(*,*) 'mdl_lamWS__exp__3 = ', MDL_LAMWS__EXP__3
      WRITE(*,*) 'mdl_CKM1x3 = ', MDL_CKM1X3
      WRITE(*,*) 'mdl_CKM2x1 = ', MDL_CKM2X1
      WRITE(*,*) 'mdl_CKM2x2 = ', MDL_CKM2X2
      WRITE(*,*) 'mdl_CKM2x3 = ', MDL_CKM2X3
      WRITE(*,*) 'mdl_CKM3x1 = ', MDL_CKM3X1
      WRITE(*,*) 'mdl_CKM3x2 = ', MDL_CKM3X2
      WRITE(*,*) 'mdl_CKM3x3 = ', MDL_CKM3X3
      WRITE(*,*) 'mdl_nb__2__exp__0_25 = ', MDL_NB__2__EXP__0_25
      WRITE(*,*) 'mdl_vev = ', MDL_VEV
      WRITE(*,*) 'mdl_MZ__exp__2 = ', MDL_MZ__EXP__2
      WRITE(*,*) 'mdl_MZ__exp__4 = ', MDL_MZ__EXP__4
      WRITE(*,*) 'mdl_sqrt__2 = ', MDL_SQRT__2
      WRITE(*,*) 'mdl_MH__exp__6 = ', MDL_MH__EXP__6
      WRITE(*,*) 'mdl_MT__exp__6 = ', MDL_MT__EXP__6
      WRITE(*,*) 'mdl_MH__exp__4 = ', MDL_MH__EXP__4
      WRITE(*,*) 'mdl_MT__exp__4 = ', MDL_MT__EXP__4
      WRITE(*,*) 'mdl_MH__exp__2 = ', MDL_MH__EXP__2
      WRITE(*,*) 'mdl_MT__exp__2 = ', MDL_MT__EXP__2
      WRITE(*,*) 'mdl_vev__exp__2 = ', MDL_VEV__EXP__2
      WRITE(*,*) 'mdl_CphidL2__exp__2 = ', MDL_CPHIDL2__EXP__2
      WRITE(*,*) 'mdl_vev__exp__4 = ', MDL_VEV__EXP__4
      WRITE(*,*) 'mdl_lam = ', MDL_LAM
      WRITE(*,*) 'mdl_yb = ', MDL_YB
      WRITE(*,*) 'mdl_yc = ', MDL_YC
      WRITE(*,*) 'mdl_ym = ', MDL_YM
      WRITE(*,*) 'mdl_yt = ', MDL_YT
      WRITE(*,*) 'mdl_ytau = ', MDL_YTAU
      WRITE(*,*) 'mdl_muH = ', MDL_MUH
      WRITE(*,*) 'mdl_MH__exp__12 = ', MDL_MH__EXP__12
      WRITE(*,*) 'mdl_MH__exp__10 = ', MDL_MH__EXP__10
      WRITE(*,*) 'mdl_MH__exp__8 = ', MDL_MH__EXP__8
      WRITE(*,*) 'mdl_vev__exp__3 = ', MDL_VEV__EXP__3
      WRITE(*,*) 'mdl_conjg__CKM1x1 = ', MDL_CONJG__CKM1X1
      WRITE(*,*) 'mdl_conjg__CKM1x2 = ', MDL_CONJG__CKM1X2
      WRITE(*,*) 'mdl_conjg__CKM1x3 = ', MDL_CONJG__CKM1X3
      WRITE(*,*) 'mdl_conjg__CKM2x1 = ', MDL_CONJG__CKM2X1
      WRITE(*,*) 'mdl_conjg__CKM2x2 = ', MDL_CONJG__CKM2X2
      WRITE(*,*) 'mdl_conjg__CKM2x3 = ', MDL_CONJG__CKM2X3
      WRITE(*,*) 'mdl_conjg__CKM3x1 = ', MDL_CONJG__CKM3X1
      WRITE(*,*) 'mdl_conjg__CKM3x2 = ', MDL_CONJG__CKM3X2
      WRITE(*,*) 'mdl_conjg__CKM3x3 = ', MDL_CONJG__CKM3X3
      WRITE(*,*) 'mdl_aEW = ', MDL_AEW
      WRITE(*,*) 'mdl_MW = ', MDL_MW
      WRITE(*,*) 'mdl_sqrt__aEW = ', MDL_SQRT__AEW
      WRITE(*,*) 'mdl_ee = ', MDL_EE
      WRITE(*,*) 'mdl_MW__exp__2 = ', MDL_MW__EXP__2
      WRITE(*,*) 'mdl_sw2 = ', MDL_SW2
      WRITE(*,*) 'mdl_ee__exp__2 = ', MDL_EE__EXP__2
      WRITE(*,*) 'mdl_MW__exp__12 = ', MDL_MW__EXP__12
      WRITE(*,*) 'mdl_MW__exp__10 = ', MDL_MW__EXP__10
      WRITE(*,*) 'mdl_MW__exp__8 = ', MDL_MW__EXP__8
      WRITE(*,*) 'mdl_MW__exp__6 = ', MDL_MW__EXP__6
      WRITE(*,*) 'mdl_MW__exp__4 = ', MDL_MW__EXP__4
      WRITE(*,*) 'mdl_AH = ', MDL_AH
      WRITE(*,*) 'mdl_cw = ', MDL_CW
      WRITE(*,*) 'mdl_sqrt__sw2 = ', MDL_SQRT__SW2
      WRITE(*,*) 'mdl_sw = ', MDL_SW
      WRITE(*,*) 'mdl_g1 = ', MDL_G1
      WRITE(*,*) 'mdl_gw = ', MDL_GW
      WRITE(*,*) 'mdl_ee__exp__4 = ', MDL_EE__EXP__4
      WRITE(*,*) 'mdl_sw__exp__4 = ', MDL_SW__EXP__4
      WRITE(*,*) 'mdl_ee__exp__3 = ', MDL_EE__EXP__3
      WRITE(*,*) 'mdl_sw__exp__3 = ', MDL_SW__EXP__3
      WRITE(*,*) 'mdl_cw__exp__2 = ', MDL_CW__EXP__2
      WRITE(*,*) 'mdl_sw__exp__2 = ', MDL_SW__EXP__2
      WRITE(*,*) 'mdl_ee__exp__6 = ', MDL_EE__EXP__6
      WRITE(*,*) 'mdl_sw__exp__6 = ', MDL_SW__EXP__6
      WRITE(*,*) 'mdl_ee__exp__5 = ', MDL_EE__EXP__5
      WRITE(*,*) 'mdl_sw__exp__5 = ', MDL_SW__EXP__5
      WRITE(*,*) 'mdl_cw__exp__3 = ', MDL_CW__EXP__3
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_sqrt__aS = ', MDL_SQRT__AS
      WRITE(*,*) 'mdl_G__exp__2 = ', MDL_G__EXP__2
      WRITE(*,*) 'mdl_GH = ', MDL_GH
      WRITE(*,*) 'mdl_Gphi = ', MDL_GPHI
