name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "madminer/**"
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"
      - "madminer/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-docs:
    needs: []
    runs-on: ubuntu-latest
    steps:
    - name: "Set up GitHub Actions"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: "Install Python dependencies"
      run: |
        python -m pip install --upgrade uv
        uv pip install --system --upgrade pip setuptools wheel
        uv pip install --system ".[docs]"
        uv pip list --system
    - name: "Build documentation"
      run: |
        make docs
