name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "madminer/**"
      - "setup.py"
  pull_request:
    branches:
      - main
    paths:
      - "docs/**"
      - "madminer/**"
      - "setup.py"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-docs:
    needs: []
    runs-on: ubuntu-latest
    steps:
    - name: "Set up GitHub Actions"
      uses: actions/checkout@v3
    - name: "Set up Python"
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: "Install Python dependencies"
      run: |
        pip install --no-cache-dir --upgrade pip setuptools wheel
        pip install --no-cache-dir --quiet ".[docs]"
        pip list
    - name: "Build documentation"
      run: |
        make docs
