name: Publish artifacts

on:
  release:
    ### NOTE:
    ###
    ### There are multiple types of release trigger events.
    ### Ref: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release
    ###
    ### Given that GitHub allows the creation of 'release'
    ### and 'pre-release' publications to differentiate between
    ### production and beta releases, the trigger type to use,
    ### as it wraps them both, must be 'published'.
    types: [published]

jobs:

  package:
    needs: []
    runs-on: ubuntu-latest
    steps:
    - name: "Set up GitHub Actions"
      uses: actions/checkout@v4
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: "Build Python package"
      run: |
        pipx run build --installer uv
    - name: "Publish Python package"
      uses: pypa/gh-action-pypi-publish@v1.8.14
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        verify-metadata: true
        print-hash: true
